// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esdjghfysppanwwogiud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzZGpnaGZ5c3BwYW53d29naXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzYyMzcsImV4cCI6MjA2MTE1MjIzN30.ZbdZK_t8MpZ1KcSPxbMQx-nm0yXb94gJvEVbC9YE840";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);